import os
import sendgrid
from sendgrid.helpers.mail import Mail, Email, To, Content
from agents import Agent, Runner, function_tool
from models import ChatSummary


# Chat summary agent for generating email content
chat_summary_agent = Agent(
    name="Chat Summary Generator",
    instructions="""Generate a professional summary of the conversation for an email notification.
Extract key information about what was discussed, the user's interests, and any notable points.
Be concise but comprehensive. Focus on what would be useful for follow-up.""",
    output_type=ChatSummary,
    model="gpt-4o-mini"
)


@function_tool
async def send_contact_email(email: str, name: str = "Visitor", notes: str = "", conversation_history: str = "") -> dict:
    """Send an email when a user provides their contact information.
    This sends a professional email to Sam with the user's details, a conversation summary, and full transcript.
    PROACTIVELY offer this service to users - suggest that you can send Human Sam an email on their behalf.
    The user MUST provide their email address so Sam knows who to respond to.

    Args:
        email: The user's email address (REQUIRED - ask for it before calling this tool)
        name: The user's name if provided (Recommended - ask for it before calling this tool)
        notes: Any additional notes about the conversation
        conversation_history: The full conversation transcript
    """
    # Generate AI summary
    result = await Runner.run(
        chat_summary_agent,
        f"User: {name}\nEmail: {email}\nNotes: {notes}\nConversation:\n{conversation_history}"
    )
    summary = result.final_output

    # Build HTML email with collapsible transcript
    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2c3e50;">New Contact from Career Website</h2>

        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 15px;">
            <h3 style="margin-top: 0; color: #34495e;">Contact Information</h3>
            <p><strong>Name:</strong> {summary.user_name}</p>
            <p><strong>Email:</strong> <a href="mailto:{summary.user_email}">{summary.user_email}</a></p>
        </div>

        <div style="background: #e8f4f8; padding: 15px; border-radius: 8px; margin-bottom: 15px;">
            <h3 style="margin-top: 0; color: #2980b9;">AI-Generated Summary</h3>
            <p><strong>Topics Discussed:</strong> {', '.join(summary.topics_discussed)}</p>
            <p><strong>User Interests:</strong> {summary.user_interests}</p>
            <p><strong>Conversation Sentiment:</strong> {summary.conversation_sentiment}</p>
            <p><strong>Notable Questions:</strong></p>
            <ul>
                {''.join(f'<li>{q}</li>' for q in summary.notable_questions)}
            </ul>
        </div>

        {f'<div style="background: #fff3cd; padding: 15px; border-radius: 8px; margin-bottom: 15px;"><h3 style="margin-top: 0; color: #856404;">Additional Notes</h3><p>{notes}</p></div>' if notes else ''}

        <details style="background: #f1f1f1; padding: 15px; border-radius: 8px;">
            <summary style="cursor: pointer; font-weight: bold; color: #555;">View Full Conversation Transcript</summary>
            <pre style="white-space: pre-wrap; font-family: monospace; font-size: 12px; margin-top: 10px; background: #fff; padding: 10px; border-radius: 4px;">{conversation_history}</pre>
        </details>

        <hr style="margin-top: 20px; border: none; border-top: 1px solid #ddd;">
        <p style="color: #888; font-size: 12px;">This email was automatically generated by your Career Conversation AI assistant.</p>
    </body>
    </html>
    """

    # Send via SendGrid
    try:
        sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
        from_email = Email(os.environ.get('SENDGRID_FROM_EMAIL'))
        to_email = To(os.environ.get('SENDGRID_TO_EMAIL'))
        subject = f"New Contact: {summary.user_name} ({summary.user_email})"
        content = Content("text/html", html_content)
        mail = Mail(from_email, to_email, subject, content).get()
        response = sg.client.mail.send.post(request_body=mail)

        print(f"Email sent! Status: {response.status_code}")

        return {
            "status": "success",
            "message": f"Email sent successfully! Sam will receive your message and contact information, and will respond to {email} soon."
        }
    except Exception as e:
        error_msg = str(e)

        if "403" in error_msg or "Forbidden" in error_msg:
            return {
                "status": "error",
                "message": f"I wasn't able to send the email due to a sender verification issue. But don't worry - I've recorded your information ({email}). Sam will follow up with you soon!"
            }
        elif "401" in error_msg or "Unauthorized" in error_msg:
            return {
                "status": "error",
                "message": f"I encountered an authentication issue sending the email. Your contact info ({email}) has been noted, and Sam will reach out to you!"
            }
        else:
            return {
                "status": "error",
                "message": f"I had trouble sending the email, but I've noted your contact information ({email}). Sam will get back to you soon!"
            }
